@startuml
'https://plantuml.com/sequence-diagram


!theme cerulean
skinparam backgroundColor #EEF2F7
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #2471A3
skinparam titleFontColor #2471A3
skinparam sequenceArrowThickness 2
skinparam defaultTextAlignment center
skinparam sequenceParticipantBorderThickness 2
skinparam sequenceParticipantFontColor white
skinparam sequenceLifeLineBorderColor #2471A3
skinparam sequenceLifeLineBorderThickness 1.5
skinparam sequenceParticipantBackgroundColor #2471A3
skinparam sequenceParticipantBorderColor #2471A3
skinparam ArrowColor #2471A3
skinparam ArrowThickness 2

skinparam sequenceLifeLineBackgroundColor #D0D3D4

TITLE "UC09"
actor Administrator

Administrator -> System : Request to get a list of all devices in a house, grouped by device functionality types and location.

System --> Administrator : Returns a list of all devices in a house, grouped by device functionality types and location.

@enduml