@startuml
!theme cerulean-outline

skinparam backgroundColor #EEF2F7
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #2471A3
skinparam titleFontColor #2471A3
skinparam sequenceArrowThickness 2
skinparam defaultTextAlignment center
skinparam sequenceParticipantBorderThickness 2
skinparam sequenceParticipantFontColor #EEF2F7
skinparam sequenceLifeLineBorderColor #2471A3
skinparam sequenceLifeLineBorderThickness 1.5
skinparam sequenceParticipantBackgroundColor #2471A3
skinparam sequenceParticipantBorderColor #2471A3
skinparam ArrowColor #2471A3
skinparam ArrowThickness 2
skinparam sequenceLifeLineBackgroundColor #D0D3D4


title UC01: Configure House Location

[o-> ":Ctrl01" : configureLocation(args)
note left
args:
street, doorNumber,
zipCode, city,
country, latitude, longitude
end note
activate ":Ctrl01"
":Ctrl01" -> ":House" : configureLocation(args)
activate ":House"
":House" -> ":LocationFactory" : createLocation(args)
activate ":LocationFactory"
":LocationFactory" -> ":LocationFactory" : new Location(args)
":LocationFactory" -> ":House" : <font color="green">location </font>
deactivate ":LocationFactory"
":House" --> ":Ctrl01" : <font color="green">location </font>
deactivate ":House"
":Ctrl01" -> ":LocationMapper" : locationToDto(location)
activate ":LocationMapper"
":LocationMapper" -> ":LocationMapper" : new LocationDTO(location.getters())
":LocationMapper" --> ":Ctrl01" : <font color="green">locationDTO </font>
deactivate ":LocationMapper"
[o<-- ":Ctrl01": <font color="green">locationDTO </font>
deactivate ":Ctrl01"

@enduml