@startuml
!theme cerulean-outline

skinparam backgroundColor #EEF2F7
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #2471A3
skinparam titleFontColor #2471A3
skinparam sequenceArrowThickness 2
skinparam defaultTextAlignment center
skinparam sequenceParticipantBorderThickness 2
skinparam sequenceParticipantFontColor #EEF2F7
skinparam sequenceLifeLineBorderColor #2471A3
skinparam sequenceLifeLineBorderThickness 1.5
skinparam sequenceParticipantBackgroundColor #2471A3
skinparam sequenceParticipantBorderColor #2471A3
skinparam ArrowColor #2471A3
skinparam ArrowThickness 2
skinparam sequenceLifeLineBackgroundColor #D0D3D4

title UC02 - Add new Room to House

[o-> ":Ctrl02" : addRoomToHouse(RoomDTO)
activate ":Ctrl02"
":Ctrl02" -> ":House" : addRoom(name, houseFloor, \nheight, width, deviceFactory, \ndimensionsFactory)
activate ":House"
":House" -> ":RoomFactory" : createRoom(name, floor, \nrepository, deviceFactory, \ndimensionsFactory)
activate ":RoomFactory"
":RoomFactory" ->":Room" :createRoom(name, floor, \nrepository, deviceFactory, \ndimensionsFactory)
activate ":Room"
":Room" -> ":Room" : validateArguments (name, floor, \nrepository, deviceFactory, \ndimensionsFactory)
":Room" --> ":RoomFactory" : <font color="green">newRoom
deactivate ":Room"
":RoomFactory" --> ":House" : <font color="green">newRoom
deactivate ":RoomFactory"
":Ctrl02" <-- ":House" : <font color="green">newRoom
deactivate ":House"
[o<-- ":Ctrl02": <font color="green">true </font>

@enduml