@startuml
!theme cerulean-outline

skinparam backgroundColor #EEF2F7
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #2471A3
skinparam titleFontColor #2471A3
skinparam sequenceArrowThickness 2
skinparam defaultTextAlignment center
skinparam sequenceParticipantBorderThickness 2
skinparam sequenceParticipantFontColor #EEF2F7
skinparam sequenceLifeLineBorderColor #2471A3
skinparam sequenceLifeLineBorderThickness 1.5
skinparam sequenceParticipantBackgroundColor #2471A3
skinparam sequenceParticipantBorderColor #2471A3
skinparam CollectionsBorderColor #000000
skinparam CollectionsBackgroundColor #2471A3
skinparam CollectionsFontColor #EEF2F7
skinparam ArrowColor #2471A3
skinparam ArrowThickness 2
skinparam sequenceLifeLineBackgroundColor #D0D3D4

title UC07 - Add a sensor to an existing device in a room

participant ":Ctrl07" as C
participant ":House" as H
participant ":RoomMapper" as RM
participant ":Room" as R
participant ":DeviceMapper" as DM
participant ":Device" as D
participant ":SensorCatalog" as SC
collections ":SensorFunctionality" as SF
participant ":Sensor" as S
ref over C, H, RM, R : UC3A: to List Rooms
ref over C, H, RM, R, DM, D : UC6A: to List Devices in Room

C -> D : getSensorFunctionalities(deviceDTO : DeviceDTO)
activate D
D -> SC : getSensorFunctionalities()
activate SC
SC -> SF : getSensorFunctionalities()
activate SF
SF --> SC : <font color="green"> sensorFunctionalities : List<SensorFunctionality> </font>
deactivate SF
SC --> D : <font color="green"> sensorFunctionalities : List<SensorFunctionality>  </font>
deactivate SC
D --> C : <font color="green"> sensorFunctionalities : List<SensorFunctionality>  </font>
deactivate D
C -> D : addSensor (sensorModel : String, name : String, \n_sensorCatalogue: SensorCatalogue, valueFactoryImpl : ValueFactoryImpl)
activate D
D -> SC : getSensor (strModel : String, SENSOR_PATH, \nname: String, valueFactory: ValueFactory)
activate SC
SC-> SC : getSensor (sensorModel : String, sensorPath: String, \nname: String, valueFactory: ValueFactory)
SC --> D : <font color="green"> sensor : Sensor
deactivate SC
D -> S :  sensorExists(name : String) : boolean
activate S
S --> D : <font color="green"> getName (name) </font>
deactivate S
D --> C : <font color="green"> sensor : Sensor </font>
deactivate D
[o<-- C : <font color="green"> True </font>
deactivate C

@enduml