@startuml
!theme cerulean-outline

skinparam backgroundColor #EEF2F7
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #2471A3
skinparam titleFontColor #2471A3
skinparam sequenceArrowThickness 2
skinparam defaultTextAlignment center
skinparam sequenceParticipantBorderThickness 2
skinparam sequenceParticipantFontColor #EEF2F7
skinparam sequenceLifeLineBorderColor #2471A3
skinparam sequenceLifeLineBorderThickness 1.5
skinparam sequenceParticipantBackgroundColor #2471A3
skinparam sequenceParticipantBorderColor #2471A3
skinparam ArrowColor #2471A3
skinparam ArrowThickness 2
skinparam sequenceLifeLineBackgroundColor #D0D3D4

title UC08A - Deactivate a device
ref over ":Ctrl08",":House", ":Room" : UC6: to List Devices
'[o-> ":Ctrl08" : getDevicesFromHouse()
'activate ":Ctrl08"
'":Ctrl08" -> ":House" : getDevices(house)
'
'
'activate ":House"
'":House" -> ":Room" : getDevices()
'activate ":Room"
'":House" <-- ":Room" : <font color="green"> List<Device> </font>
'deactivate ":Room"
'":Ctrl08" <-- ":House" : <font color="green"> List<Device> </font>
'deactivate ":House"
":Ctrl08" -> ":DeviceMapper" : Domain2DTO(device)
activate ":DeviceMapper"
":DeviceMapper" -> ":DeviceMapper" : Domain2DTO(device)
":Ctrl08" <-- ":DeviceMapper" : <font color="green"> Map<DeviceDTO, Device> </font>
deactivate ":DeviceMapper"



[o<-- ":Ctrl08" : <font color="green"> Map<DeviceDTO, Device> </font>
deactivate ":Ctrl08"

[o-> ":Ctrl08" : deactivate (deviceDTO)
activate ":Ctrl08"
":Ctrl08" -> ":Ctrl08" : getDeviceDto(deviceDTO.name)\n<font color="green"> DeviceDTO</font>
":Ctrl08" -> ":Ctrl08" : _devicesDTOAndDevices.get(DeviceDTO)\n<font color="green"> Device </font>
":Ctrl08" -> ":House" : deactivateDevice (device)
activate ":House"
":House" -> ":Device" : switchDevice (false)
activate ":Device"
":Device" -> ":Device" : switchDevice (false)
":House" <-- ":Device" : <font color="green"> true </font>
deactivate ":Device"
":Ctrl08" <-- ":House" : <font color="green"> true </font>
deactivate ":House"
[o<-- ":Ctrl08" : <font color="green"> true </font>
deactivate ":Ctrl08"


@enduml