@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEF2F7
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor #2471A3
skinparam titleFontColor #2471A3
skinparam titleFontSize 20
skinparam sequenceArrowThickness 2
skinparam defaultTextAlignment center
skinparam sequenceParticipantBorderThickness 2
skinparam sequenceParticipantFontColor #EEF2F7
skinparam sequenceLifeLineBorderColor #2471A3
skinparam sequenceLifeLineBorderThickness 1.5
skinparam sequenceParticipantBackgroundColor #2471A3
skinparam sequenceParticipantBorderColor #2471A3
skinparam ArrowColor #2471A3
skinparam ArrowThickness 2
skinparam sequenceLifeLineBackgroundColor #D0D3D4

title UC09 - Get a list of all devices in a house, grouped by device functionality types. It must include device location.
activate ":Ctrl09"
[o-> ":Ctrl09" : getDevicesByRoomAndFunctionality()
activate ":House"
":Ctrl09" -> ":House" : getDevicesByRoomAndFunctionality(DevicesByFunctionality)
":House" -> ":DevicesByFunctionality" : getGroupedResult()
activate ":DevicesByFunctionality"

loop
":DevicesByFunctionality" -> ":Room" : getDevices()
activate ":Room"

loop
":Room" -> ":Device" : getSensors()
activate ":Device"
loop
":Device" -> "Sensor" : getSensorFunctionality()
activate "Sensor"
"Sensor" -> "D1:DeviceRoomDTO" ** : DeviceRoomDTO(String device, String room)
activate "D1:DeviceRoomDTO"
"D1:DeviceRoomDTO" --> "Sensor" : <font color="green">DeviceRoomDTO</font>
deactivate "D1:DeviceRoomDTO"
"Sensor" -> "Sensor" : list.add(DeviceRoomDTO)
"Sensor" -> "Sensor" : map.put(sensorFunctionality, list)
End
End
deactivate ":Room"
deactivate ":Device"
End
deactivate "D1:DeviceRoomDTO"
"Sensor" --> ":DevicesByFunctionality" : <font color="green">Map<String, List<DeviceRoomDTO>> </font>
deactivate "Sensor"
":DevicesByFunctionality" --> ":House": <font color="green">Map<String, List<DeviceRoomDTO>> </font>
deactivate ":DevicesByFunctionality"
":House" --> ":Ctrl09" : <font color="green">Map<String, List<DeviceRoomDTO>> </font>
deactivate ":House"
[o<-- ":Ctrl09": <font color="green">Map<String, List<DeviceRoomDTO>> </font>
@enduml